spring.application.name=crudeapi

spring.datasource.url=jdbc:mysql://localhost:3306/crude_operationDB
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-SQL=true
spring.jpa.propertiese.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
